//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTraSach
    {
        public int id_BaoCaoTraSach { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public string HoTen { get; set; }
        public string TenSach { get; set; }
    }
}
